"""Add status to taste_profiles

Revision ID: 1df9daebfd12
Revises: a9929eeffeba
Create Date: 2026-09-21 13:40:17.619570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1df9daebfd12'
down_revision: Union[str, Sequence[str], None] = 'a9929eeffeba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taste_profiles', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('taste_profiles', sa.Column('error', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taste_profiles', 'error')
    op.drop_column('taste_profiles', 'status')
    # ### end Alembic commands ###
