"""Add taste_profiles table

Revision ID: a9929eeffeba
Revises: 356c86d2403c
Create Date: 2026-09-21 10:49:01.565167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9929eeffeba'
down_revision: Union[str, Sequence[str], None] = '356c86d2403c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taste_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=False),
    sa.Column('entries_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_taste_profiles_id'), 'taste_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taste_profiles_id'), table_name='taste_profiles')
    op.drop_table('taste_profiles')
    # ### end Alembic commands ###
